server:
  port: 8090
  servlet:
    context-path: /
spring:  mvc:    view:      prefix: /pages/views/
      suffix: .html
  application:   #定义服务名称
    name: fm-web
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: fm-web-8090        #定义微服务的名称
    prefer-ip-address: true                #是否显示IP和端口
      